---
title: "JiT Summary"
output:
  html_document:
    df_print: paged
  word_document: default
---
The following chunk of code reads in and merges the sheets from the workbook, then removes rows where the "Date Coded" field was left blank:

```{r processing}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
state <- c("Kansas","Nebraska","Wyoming ", "North Dakota")

df <- data.frame()

for (states in state){
  
  df <- rbind(df,read_excel("C:/Users/DavidMcCullough/Marzano Research/MZR - Share/10_REL/Task 6-Research/CE6.6_JiT/Data Entry/CE6.6.1 Data Entry_FINAL.xlsx", 
             sheet = states)[,1:26])
}

df_coded <- df[!is.na(df$`Date Coded`),]

vars <- names(df)

```

The following code chunk generates barplots for each of the TBD variables in the datasets. 

```{r, echo= FALSE}
results <- list()

variable <- 5
temp <- df %>% 
  filter(!is.na(get(vars[variable]))) %>% 
  group_by(State, get(vars[variable])) %>% 
  tally() %>% 
  mutate(percent = round((n/sum(n))*100,digits = 1))

names(temp)[2] <- vars[variable]
```

```{r, fig.width = 9, fig.height = 4, out.width='100%', fig.align= "center"}
ggplot(data = temp, aes(x=factor(get(vars[variable])),y=percent,fill=factor(get(vars[variable])))) + 
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) + 
  facet_grid(cols = vars(State)) + 
  theme(axis.text.x = element_blank(),axis.title = element_blank(),plot.title = element_text(hjust = 0.5)) +
  labs(fill="Response") + 
  ggtitle(tools::toTitleCase(vars[variable]))
```

```{r}
knitr::kable(spread(data = temp[,-4],key = get(vars[variable]),value = n))
knitr::kable(spread(data = temp[,-3],key = get(vars[variable]),value = percent))
```
